---
name: Cleanup Old Images
on:
  schedule:
    - cron: "12 7 * * *"  # 7:05 UTC everyday
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          older-than: 90 days
          delete-orphaned-images: true
